/**
 * mockDatabase.js - BACKWARD COMPATIBILITY WRAPPER
 * 
 * This file now re-exports all functions from databaseService.js
 * to maintain backward compatibility with existing imports.
 * 
 * The actual implementation has been moved to databaseService.js which handles:
 * - Supabase integration
 * - Offline fallback to localStorage
 * - Sync queue for offline mutations
 * - Network detection and retry logic
 * 
 * IMPORTANT: Do NOT edit this file to add custom logic.
 * All database operations should be modified in databaseService.js instead.
 * 
 * Usage:
 *   import { getMenu, saveTransaction } from '@/services/mockDatabase'
 *   // Same as before; routing automatically handled
 */

import {
  getUsers,
  saveUser,
  getHistory,
  addHistoryLog,
  clearHistory,
  getMenu,
  saveMenu,
  resetMenu,
  getInventory,
  saveInventory,
  addInventoryItem,
  updateInventoryItem,
  getTransactions,
  saveTransaction,
  updateTransactionStatus,
  clearTransactions,
  getBusinessInfo,
  saveBusinessInfo,
  getSuppliers,
  saveSuppliers,
  getRecipes,
  saveRecipe,
  getNotifications,
  addNotification,
  getUsageLogs,
  addUsageLog,
  getServiceFees,
  saveServiceFees,
} from './databaseService';

// ============================================================================
// RE-EXPORT ALL 21 FUNCTIONS FOR BACKWARD COMPATIBILITY
// ============================================================================

export {
  getUsers,
  saveUser,
  getHistory,
  addHistoryLog,
  clearHistory,
  getMenu,
  saveMenu,
  resetMenu,
  getInventory,
  saveInventory,
  addInventoryItem,
  updateInventoryItem,
  getTransactions,
  saveTransaction,
  updateTransactionStatus,
  clearTransactions,
  getBusinessInfo,
  saveBusinessInfo,
  getSuppliers,
  saveSuppliers,
  getRecipes,
  saveRecipe,
  getNotifications,
  addNotification,
  getUsageLogs,
  addUsageLog,
  getServiceFees,
  saveServiceFees,
};
